/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as AKindNamespaceNameVersionRouteImport } from './routes/a.$kind.$namespace.$name.$version'
import { Route as InspectKindNamespaceNameVersionRouteImport } from './routes/inspect.$kind.$namespace.$name.$version'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const AKindNamespaceNameVersionRoute =
  AKindNamespaceNameVersionRouteImport.update({
    id: '/a/$kind/$namespace/$name/$version',
    path: '/a/$kind/$namespace/$name/$version',
    getParentRoute: () => rootRouteImport,
  } as any)
const InspectKindNamespaceNameVersionRoute =
  InspectKindNamespaceNameVersionRouteImport.update({
    id: '/inspect/$kind/$namespace/$name/$version',
    path: '/inspect/$kind/$namespace/$name/$version',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/review': typeof ReviewRoute
  '/submit': typeof SubmitRoute
  '/a/$kind/$namespace/$name/$version': typeof AKindNamespaceNameVersionRoute
  '/inspect/$kind/$namespace/$name/$version': typeof InspectKindNamespaceNameVersionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/review': typeof ReviewRoute
  '/submit': typeof SubmitRoute
  '/a/$kind/$namespace/$name/$version': typeof AKindNamespaceNameVersionRoute
  '/inspect/$kind/$namespace/$name/$version': typeof InspectKindNamespaceNameVersionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/review': typeof ReviewRoute
  '/submit': typeof SubmitRoute
  '/a/$kind/$namespace/$name/$version': typeof AKindNamespaceNameVersionRoute
  '/inspect/$kind/$namespace/$name/$version': typeof InspectKindNamespaceNameVersionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/review'
    | '/submit'
    | '/a/$kind/$namespace/$name/$version'
    | '/inspect/$kind/$namespace/$name/$version'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/review'
    | '/submit'
    | '/a/$kind/$namespace/$name/$version'
    | '/inspect/$kind/$namespace/$name/$version'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/review'
    | '/submit'
    | '/a/$kind/$namespace/$name/$version'
    | '/inspect/$kind/$namespace/$name/$version'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  ReviewRoute: typeof ReviewRoute
  SubmitRoute: typeof SubmitRoute
  AKindNamespaceNameVersionRoute: typeof AKindNamespaceNameVersionRoute
  InspectKindNamespaceNameVersionRoute: typeof InspectKindNamespaceNameVersionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$kind/$namespace/$name/$version': {
      id: '/a/$kind/$namespace/$name/$version'
      path: '/a/$kind/$namespace/$name/$version'
      fullPath: '/a/$kind/$namespace/$name/$version'
      preLoaderRoute: typeof AKindNamespaceNameVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect/$kind/$namespace/$name/$version': {
      id: '/inspect/$kind/$namespace/$name/$version'
      path: '/inspect/$kind/$namespace/$name/$version'
      fullPath: '/inspect/$kind/$namespace/$name/$version'
      preLoaderRoute: typeof InspectKindNamespaceNameVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  ReviewRoute: ReviewRoute,
  SubmitRoute: SubmitRoute,
  AKindNamespaceNameVersionRoute: AKindNamespaceNameVersionRoute,
  InspectKindNamespaceNameVersionRoute: InspectKindNamespaceNameVersionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
