import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { Ajv2020 } from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";
import yaml from "js-yaml";

const root = path.resolve(import.meta.dirname, "..");
const manifestSourcePath = path.join(root, "spec", "manifest.schema.yaml");
const registrySourcePath = path.join(root, "spec", "registry.schema.yaml");
const pythonPath = path.join(root, "src", "molhub", "schema", "manifest.schema.yaml");
const typescriptManifestPath = path.join(
  root,
  "packages",
  "typescript",
  "src",
  "generated-manifest-schema.ts",
);
const typescriptRegistryPath = path.join(
  root,
  "packages",
  "typescript",
  "src",
  "generated-registry-schema.ts",
);
const typescriptManifestValidatorPath = path.join(
  root,
  "packages",
  "typescript",
  "src",
  "generated-manifest-validator.ts",
);
const typescriptRegistryValidatorPath = path.join(
  root,
  "packages",
  "typescript",
  "src",
  "generated-registry-validator.ts",
);
const check = process.argv.includes("--check");

const manifestSource = await readFile(manifestSourcePath, "utf8");
const registrySource = await readFile(registrySourcePath, "utf8");

function typescriptBundle(source: string, sourceName: string, exportName: string): string {
  const parsed = yaml.load(source);
  if (typeof parsed !== "object" || parsed === null) {
    throw new Error(`${sourceName} does not contain a JSON Schema object.`);
  }
  return [
    `// Generated from spec/${sourceName} by scripts/sync-contract.ts.`,
    "// Do not edit this file directly.",
    `export const ${exportName} = ${JSON.stringify(parsed, null, 2)} as const;`,
    "",
  ].join("\n");
}

function typescriptValidator(source: string, sourceName: string): string {
  const schema = yaml.load(source);
  if (typeof schema !== "object" || schema === null) {
    throw new Error(`${sourceName} does not contain a JSON Schema object.`);
  }
  const ajv = new Ajv2020({
    allErrors: true,
    allowUnionTypes: true,
    strictRequired: false,
    code: { source: true, esm: true },
  });
  const code = standaloneCode(ajv, ajv.compile(schema)).replaceAll(
    'require("ajv/dist/runtime/ucs2length").default',
    "((value) => Array.from(value).length)",
  );
  if (code.includes("require(")) {
    throw new Error(`${sourceName} generated a CommonJS runtime dependency.`);
  }
  return [
    `// Generated from spec/${sourceName} by scripts/sync-contract.ts.`,
    "// Runtime-safe for browsers and Cloudflare Workers: no eval or new Function.",
    "// @ts-nocheck",
    code,
    "",
  ].join("\n");
}

const outputs = [
  { path: pythonPath, contents: manifestSource },
  {
    path: typescriptManifestPath,
    contents: typescriptBundle(manifestSource, "manifest.schema.yaml", "MANIFEST_SCHEMA"),
  },
  {
    path: typescriptRegistryPath,
    contents: typescriptBundle(registrySource, "registry.schema.yaml", "REGISTRY_SCHEMA"),
  },
  {
    path: typescriptManifestValidatorPath,
    contents: typescriptValidator(manifestSource, "manifest.schema.yaml"),
  },
  {
    path: typescriptRegistryValidatorPath,
    contents: typescriptValidator(registrySource, "registry.schema.yaml"),
  },
];

if (check) {
  const drifted: string[] = [];
  for (const output of outputs) {
    let current = "";
    try {
      current = await readFile(output.path, "utf8");
    } catch {
      // Missing generated output is contract drift too.
    }
    if (current !== output.contents) drifted.push(path.relative(root, output.path));
  }
  if (drifted.length > 0) {
    throw new Error(
      `Generated contract files are stale: ${drifted.join(", ")}. Run npm run contract:sync.`,
    );
  }
  process.stdout.write("Contract bundles match the schemas under spec/.\n");
} else {
  for (const output of outputs) await writeFile(output.path, output.contents, "utf8");
  process.stdout.write("Updated Python and TypeScript contract bundles.\n");
}
