// Generated from spec/manifest.schema.yaml by scripts/sync-contract.ts.
// Do not edit this file directly.
export const MANIFEST_SCHEMA = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://molcrafts.org/schema/molhub/manifest/1",
  "title": "molhub artifact manifest",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "kind",
    "namespace",
    "name",
    "version",
    "title",
    "artifacts"
  ],
  "properties": {
    "schema_version": {
      "const": 1
    },
    "kind": {
      "enum": [
        "dataset",
        "model",
        "plugin"
      ]
    },
    "namespace": {
      "$ref": "#/$defs/segment"
    },
    "name": {
      "$ref": "#/$defs/segment"
    },
    "version": {
      "description": "Required. A coordinate without a version cannot name an immutable artifact, so molhub rejects one rather than guessing \"latest\".",
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]*$"
    },
    "title": {
      "type": "string",
      "minLength": 1
    },
    "description": {
      "type": "string"
    },
    "license": {
      "description": "SPDX identifier, e.g. CC0-1.0.",
      "type": "string"
    },
    "doi": {
      "description": "The persistent identifier for exactly this version, when upstream mints one. This is what makes \"which version\" precise; the locators must pin the same version, and a digest is a secondary cross-check.",
      "type": "string",
      "pattern": "^10[.][0-9]{4,}/.+$"
    },
    "artifacts": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/$defs/artifact"
      }
    },
    "targets": {
      "description": "Declarative only. Nothing in the transport or resolution layers parses bytes according to this; it is for display and for downstream consumers.",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "graph_level": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "atom_level": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  },
  "$defs": {
    "segment": {
      "type": "string",
      "pattern": "^[a-z0-9][a-z0-9-]*$"
    },
    "artifact": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "role",
        "filename",
        "locators"
      ],
      "anyOf": [
        {
          "required": [
            "digest"
          ]
        },
        {
          "required": [
            "size"
          ]
        }
      ],
      "properties": {
        "role": {
          "description": "How consumers refer to this file -- main, exclude, weights...",
          "type": "string",
          "minLength": 1
        },
        "filename": {
          "type": "string",
          "minLength": 1
        },
        "format": {
          "description": "Stable, machine-readable identifier for the bytes in this artifact. Consumers must use this field instead of guessing from the filename. Examples include extxyz, npz, csv, and molrec-zarr-v3.",
          "type": "string",
          "pattern": "^[a-z0-9][a-z0-9._+-]*$"
        },
        "media_type": {
          "description": "Optional IANA-style media type for transport and display. Parameters are intentionally excluded; manifests describe the stored artifact, not one particular HTTP response.",
          "type": "string",
          "pattern": "^[A-Za-z0-9!#$&^_.+-]+/[A-Za-z0-9!#$&^_.+-]+$"
        },
        "digest": {
          "description": "Whatever the platform publishes for this file, copied verbatim -- Figshare and Zenodo publish md5, HuggingFace a sha256 LFS OID. Omit it when the platform publishes nothing; molhub never invents one. Its job is to confirm upstream still serves the version this manifest names. When it stops matching, upstream changed and the manifest needs a new version.",
          "type": "string",
          "oneOf": [
            {
              "pattern": "^md5:[0-9a-f]{32}$"
            },
            {
              "pattern": "^sha1:[0-9a-f]{40}$"
            },
            {
              "pattern": "^sha256:[0-9a-f]{64}$"
            },
            {
              "pattern": "^sha512:[0-9a-f]{128}$"
            }
          ]
        },
        "size": {
          "description": "Byte count, from what the platform reports or from a HEAD request's content-length. Must be at least 1: zero is not a smaller artifact, it is the shape of a failed transfer. This project's own history has a 0-byte response cached as a valid exclusion list, and since `size` may be the only cross-check an artifact carries, `size: 0` would make that exact failure verify as correct.",
          "type": "integer",
          "exclusiveMinimum": 0
        },
        "locators": {
          "description": "Ordered candidate sources; earlier entries are preferred. Each must pin a version upstream understands -- a Figshare article id alone follows whatever becomes current, so use ``figshare://<id>/v<n>``.",
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "pattern": "^[a-z][a-z0-9+.-]*://.+$"
          }
        }
      }
    }
  }
} as const;
