// Generated from spec/registry.schema.yaml by scripts/sync-contract.ts.
// Do not edit this file directly.
export const REGISTRY_SCHEMA = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://molcrafts.org/schema/molhub/registry/1",
  "title": "molhub aggregate registry",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "entries"
  ],
  "properties": {
    "schema_version": {
      "description": "Tracks this envelope, not the manifests inside it. A breaking change to the entry shape bumps this so an older client can refuse the file rather than misread it.",
      "const": 1
    },
    "entries": {
      "description": "Every manifest in the registry, ordered by `coordinate` and by nothing else. Order is part of the contract because it is what makes the build reproducible; a consumer that wants another order sorts a copy.\nMay be empty: a registry with no entries is a real state (a fresh fork, a registry mid-migration) and should build rather than fail. Emptiness is the site's problem to render, not the schema's to forbid.",
      "type": "array",
      "items": {
        "$ref": "#/$defs/entry"
      }
    }
  },
  "$defs": {
    "segment": {
      "type": "string",
      "pattern": "^[a-z0-9][a-z0-9-]*$"
    },
    "entry": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "coordinate",
        "kind",
        "namespace",
        "name",
        "version",
        "title",
        "description",
        "license",
        "doi",
        "targets",
        "artifacts"
      ],
      "properties": {
        "coordinate": {
          "description": "The canonical `kind:namespace/name@version`, spelled out in full and unique across the registry. Redundant with the four fields below, and kept anyway: it is the string a user types, the key a consumer joins on, and the anchor a URL is built from. Recomputing it in every client is how the four spellings start to drift apart.",
          "type": "string",
          "pattern": "^(dataset|model|plugin):[a-z0-9][a-z0-9-]*/[a-z0-9][a-z0-9-]*@[A-Za-z0-9][A-Za-z0-9._-]*$"
        },
        "kind": {
          "enum": [
            "dataset",
            "model",
            "plugin"
          ]
        },
        "namespace": {
          "$ref": "#/$defs/segment"
        },
        "name": {
          "$ref": "#/$defs/segment"
        },
        "version": {
          "type": "string",
          "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]*$"
        },
        "title": {
          "type": "string",
          "minLength": 1
        },
        "description": {
          "description": "Free prose, or `null` when the manifest wrote none.",
          "type": [
            "string",
            "null"
          ]
        },
        "license": {
          "description": "SPDX identifier, e.g. CC0-1.0, or `null` when unstated.",
          "type": [
            "string",
            "null"
          ]
        },
        "doi": {
          "description": "The persistent identifier for exactly this version. Nullable in the schema because the shape must be describable before it is policed — the shared `ManifestValidator` refuses a null one, and it refuses with an explanation a contributor can act on. A type error here would only say \"expected string\".",
          "type": [
            "string",
            "null"
          ],
          "pattern": "^10[.][0-9]{4,}/.+$"
        },
        "targets": {
          "description": "Declarative only, and always present: a manifest that omits the block becomes two empty lists rather than a missing key, so a consumer can map over it without a guard. Nothing in the fetch path reads this.",
          "type": "object",
          "additionalProperties": false,
          "required": [
            "graph_level",
            "atom_level"
          ],
          "properties": {
            "graph_level": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "atom_level": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "artifacts": {
          "description": "At least one, ordered by `role`. A manifest with no downloadable file names nothing and is rejected upstream by the manifest schema.",
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/artifact"
          }
        }
      }
    },
    "artifact": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "role",
        "filename",
        "format",
        "media_type",
        "locators",
        "digest",
        "size"
      ],
      "anyOf": [
        {
          "properties": {
            "digest": {
              "type": "string"
            }
          }
        },
        {
          "properties": {
            "size": {
              "type": "integer"
            }
          }
        }
      ],
      "properties": {
        "role": {
          "description": "How consumers refer to this file -- main, exclude, weights...",
          "type": "string",
          "minLength": 1
        },
        "filename": {
          "type": "string",
          "minLength": 1
        },
        "format": {
          "description": "Stable byte-format identifier, or `null` for legacy manifests.",
          "oneOf": [
            {
              "type": "null"
            },
            {
              "type": "string",
              "pattern": "^[a-z0-9][a-z0-9._+-]*$"
            }
          ]
        },
        "media_type": {
          "description": "IANA-style media type without parameters, or `null`.",
          "oneOf": [
            {
              "type": "null"
            },
            {
              "type": "string",
              "pattern": "^[A-Za-z0-9!#$&^_.+-]+/[A-Za-z0-9!#$&^_.+-]+$"
            }
          ]
        },
        "locators": {
          "description": "Ordered candidate sources; earlier entries are preferred. Copied from the manifest unchanged -- the build resolves nothing and rewrites nothing, so what a user reads here is what a client will request.",
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "pattern": "^[a-z][a-z0-9+.-]*://.+$"
          }
        },
        "digest": {
          "description": "Whatever the platform publishes for this file, copied verbatim, or `null` when it publishes nothing -- molhub never computes one. The pattern applies only when a string is present.",
          "oneOf": [
            {
              "type": "null"
            },
            {
              "type": "string",
              "pattern": "^md5:[0-9a-f]{32}$"
            },
            {
              "type": "string",
              "pattern": "^sha1:[0-9a-f]{40}$"
            },
            {
              "type": "string",
              "pattern": "^sha256:[0-9a-f]{64}$"
            },
            {
              "type": "string",
              "pattern": "^sha512:[0-9a-f]{128}$"
            }
          ]
        },
        "size": {
          "description": "Byte count, or `null`. Never `null` when `digest` is.",
          "type": [
            "integer",
            "null"
          ],
          "exclusiveMinimum": 0
        }
      }
    }
  }
} as const;
